import javafx.scene.image.Image;

import java.io.FileInputStream;

public class Convention {
	public static String WALL_PATH = "image/wall.png";
	public static String GRASS_PATH = "image/grass.png";
	public static String PLAYER_UP1_PATH = "image/player_up1.png";
	public static String PLAYER_UP2_PATH = "image/player_up2.png";
	public static String PLAYER_UP3_PATH = "image/player_up3.png";
	public static String PLAYER_LEFT1_PATH = "image/player_left1.png";
	public static String PLAYER_LEFT2_PATH = "image/player_left2.png";
	public static String PLAYER_LEFT3_PATH = "image/player_left3.png";
	public static String PLAYER_RIGHT1_PATH = "image/player_right1.png";
	public static String PLAYER_RIGHT2_PATH = "image/player_right2.png";
	public static String PLAYER_RIGHT3_PATH = "image/player_right3.png";
	public static String PLAYER_DOWN1_PATH = "image/player_down1.png";
	public static String PLAYER_DOWN2_PATH = "image/player_down2.png";
	public static String PLAYER_DOWN3_PATH = "image/player_down3.png";
	public static String BRICK_PATH = "image/brick.png";
	public static String BALLOOM_LEFT1_PATH = "image/balloom_left1.png";
	public static String BALLOOM_LEFT2_PATH = "image/balloom_left2.png";
	public static String BALLOOM_LEFT3_PATH = "image/balloom_left3.png";
	public static String BALLOOM_RIGHT1_PATH = "image/balloom_right1.png";
	public static String BALLOOM_RIGHT2_PATH = "image/balloom_right2.png";
	public static String BALLOOM_RIGHT3_PATH = "image/balloom_right3.png";
	public static String ONEAL_LEFT1_PATH = "image/oneal_left1.png";
	public static String ONEAL_LEFT2_PATH = "image/oneal_left2.png";
	public static String ONEAL_LEFT3_PATH = "image/oneal_left3.png";
	public static String ONEAL_RIGHT1_PATH = "image/oneal_right1.png";
	public static String ONEAL_RIGHT2_PATH = "image/oneal_right2.png";
	public static String ONEAL_RIGHT3_PATH = "image/oneal_right3.png";
	public static String GAME_WIN_PATH = "image/win_game.jpg";
	public static String GAME_LOSE_PATH = "image/lose_game.jpg";
	public static String BALLOOM_DEAD = "image/balloom_dead.png";
	public static String ONEAL_DEAD = "image/oneal_dead.png";
	public static String EXPLOSION_CENTER = "image/bomb_exploded.png";
	public static String EXPLOSION_HORIZONTAL = "image/explosion_horizontal.png";
	public static String EXPLOSION_VERTICAL = "image/explosion_vertical.png";
	public static String EXPLOSION_HORIZONTAL_LEFT_LAST = "image/explosion_horizontal_left_last.png";
	public static String EXPLOSION_HORIZONTAL_RIGHT_LAST = "image/explosion_horizontal_right_last.png";
	public static String EXPLOSION_VERTICAL_UP_LAST = "image/explosion_vertical_up_last.png";
	public static String EXPLOSION_VERTICAL_DOWN_LAST = "image/explosion_vertical_down_last.png";
	public static String BOMB_PATH = "image/bomb.png";
	public static String BOMB_ITEM = "image/bomb_item.png";
	public static String SPEED_ITEM = "image/speed_item.png";
	public static String FLAME_ITEM = "image/flame_item.png";
	public static String PORTAL_PATH = "image/portal.png";
	public static int PLAYER_WIDTH = 30;
	public static int PLAYER_HEIGHT = 40;
	public static int PLAYER_SPEED1 = 5;
	public static int PLAYER_SPEED2 = 10;
	public static int BALLOOM_SPEED = 5;
	public static int ONEAL_SPEED = 10;
	public static int PLAYER_FLAME_LENGTH1 = 1;
	public static int PLAYER_FLAME_LENGTH2 = 2;
	public static int PLAYER_NUMBER_OF_BOMBS1 = 1;
	public static int PLAYER_NUMBER_OF_BOMBS2 = 2;
	public static int TIME_EXPLOSION = 50;
	public static int TIME_BOMB = 3000;
	public static int PIXEL_WIDTH = 40;
	public static int PIXEL_HEIGHT = 40;
}
